### ISSUE TITLE
A bug dedected on line 13 in about.html file

### ISSUE THREAD

**Issue by ghost** [AlexRS90/personalBrand-capstone1#2]
Hi @AlexRS90 ,

Please add # to href in anchor tag for burger menu in about.html file, otherwise, it is updating the page constantly and thus closing the mobmenu continuously in the process.

Good luck with your submission! Cheers!

**Comment by AlexRS90** [comment]
Thanks a lot for your help Hope, I appreciate it!!

Cheers! 🍻
